---
- name: Add aliases to bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "# zfs {mark} ANSIBLE MANAGED BLOCK"
    block: |
      function zload() {
        sudo zfs load-key -L prompt $1 && sudo zfs mount $1
      }

      function zunload() {
        sudo zfs unmount -f $1 && sudo zfs unload-key $1
      }

      function zload-all() {
        if [[ -n "$PASS" ]]; then
          echo $PASS | sudo zfs mount -l tortoise
          echo $PASS | sudo zfs mount -l elephant
          echo $PASS | sudo zfs mount -l cheetah
          sudo zfs mount -a
          unset PASS
          zfs get mounted
        else
          echo "PASS missing.."
          exit 1
        fi
      }

      alias dev-disk-by-id-with-link="ls -l /dev/disk/by-id/* | \
        grep -E '(scsi-SATA|nvme-[^e]).*[A-Z0-9]{8}\W\->' | \
        tr -s ' ' | \
        cut -d ' ' -f 9,11 | \
        sed -e 's,\.\.\/\.\.,/dev,g'"

      alias dev-disk-by-id="ls -l /dev/disk/by-id/* | \
        grep -E '(scsi-SATA|nvme-[^e]).*[A-Z0-9]{8}\W\->' | \
        tr -s ' ' | \
        cut -d ' ' -f 9 | \
        sed -e 's,\.\.\/\.\.,/dev,g'"

      function apt-key-fix() {
        for KEY in $( \
          apt-key --keyring /etc/apt/trusted.gpg list | \
            grep -E "(([ ]{1,2}(([0-9A-F]{4}))){10})" | \
            tr -d " " | \
            grep -E "([0-9A-F]){8}\b" \
        ); do
          K=${KEY:(-8)}
          apt-key export $K | \
            sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/imported-from-trusted-gpg-$K.gpg
        done
      }
