---
- name: "Change chown for /opt"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.file:
    path: /opt
    mode: '0777'

- name: "Get latest openzfs/zfs tag"
  ansible.builtin.uri:
    url: https://api.github.com/repos/openzfs/zfs/releases/latest
    return_content: true
  register: zfs_json_reponse
  when:
    - zfs_version is not defined

- name: "Clone openzfs/zfs"
  ansible.builtin.git:
    repo: https://github.com/openzfs/zfs.git
    dest: /opt/zfs
    version: "{{ zfs_version | default(zfs_json_reponse.json.tag_name) }}"
