---
# - name: Preinstall
#   delegate_to: localhost
#   ansible.builtin.shell: |
#     rm -f ./packages/*.ipk
#     {% for package in packages %}
#       wget -P ./packages {{package.link}}
#     {% endfor %}
#   register: preinstall_stdout

- name: Prepare folder
  delegate_to: localhost
  ansible.builtin.file:
    state: "directory"
    path: "./packages"

- name: Clean folder
  delegate_to: localhost
  ansible.builtin.file:
    state: "absent"
    path: "./packages/{{ item.name }}*"
  loop: "{{ packages }}"
  when:
    - clear_packages | bool | default(false) == true

- name: Download packages
  delegate_to: localhost
  ansible.builtin.shell: |
    # wget -P ./packages {{ item.link }}
    # curl -s {{ item.link }} | grep {{ item.name }}

    wget --no-clobber -P ./packages {{ item.link }}$(curl -s {{ item.link }} | grep {{ item.name }}_ | sed 's/<[^>]*>//g ; /^$/d' | sed 's/ipk.*//' | sed 's/ *//')ipk
  retries: 5
  delay: 1
  register: result
  until: result is succeeded
  ignore_errors: true
  loop: "{{ packages }}"
