---
- name: "Install sanoid"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.shell: |
    shopt -s extglob
    apt install ./*.deb
  args:
    executable: /bin/bash
    chdir: /opt/sanoid
  register: install_packages
  changed_when: install_packages.rc == 0

- name: "Ensure sanoid systemd units are enabled"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - sanoid.timer
