---
- name: Make clean workspace
  ansible.builtin.shell: |
    uci revert prometheus-node-exporter-lua
    for line in $(uci show prometheus-node-exporter-lua | sed '1!G;h;$!d' | cut -f1 -d"="); do echo $line; uci delete $line; done
