---
- name: General install
  hosts: "{{ target | default('weather_station') }}"
  vars_files:
    - vars/main.yml
  roles:
    - { role: sudoers }
    - { role: general/ssh_config } # noqa: role-name[path]
    - { role: apps }
    - { role: general/unattended_upgrades } # noqa: role-name[path]
