---
- name: Install packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
  retries: 5
  delay: 1
  register: result
  until: result is succeeded
  loop:
    - nextdns
    - luci-app-nextdns
  when:
    - skip_install | default(false) == false
