---
- name: Preinstall
  ansible.builtin.shell: |
    scp -Or ./packages root@{{ target | default('192.168.1.1') }}:/tmp
    ssh root@{{ target | default('192.168.1.1') }} opkg install /tmp/packages/*.ipk
    ssh root@{{ target | default('192.168.1.1') }} rm -fr /tmp/packages/
