---
- name: "Openzfs/zfs > git clean # noqa: command-instead-of-module"
  ansible.builtin.shell: |
    git clean -fx
  args:
    executable: /bin/bash
    chdir: /opt/zfs
  register: git_clean
  changed_when: git_clean.rc == 0

- name: "Openzfs/zfs > ./autogen.sh"
  ansible.builtin.shell: |
    ./autogen.sh
  args:
    executable: /bin/bash
    chdir: /opt/zfs
  register: autogen
  changed_when: autogen.rc == 0

- name: "Openzfs/zfs > ./configure"
  ansible.builtin.shell: |
    ./configure --enable-systemd
  args:
    executable: /bin/bash
    chdir: /opt/zfs
  register: configure
  changed_when: configure.rc == 0

- name: "Openzfs/zfs > make -s -j$(nproc) deb-utils deb-dkms"
  ansible.builtin.shell: |
    make -j$(nproc) deb-utils deb-dkms
  args:
    executable: /bin/bash
    chdir: /opt/zfs
  register: make
  changed_when: make.rc == 0
