---
- name: "Install Docker"
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
  ignore_errors: true
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"

- name: "Reload systemd"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart docker"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.service:
    name: docker
    state: "{{ docker_restart_handler_state }}"

- name: "Ensure Docker is started and enabled at boot"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: "Ensure handlers are notified now to avoid firewall conflicts"
  ansible.builtin.meta: flush_handlers
