---
- name: "Ensure docker users are added to the docker group"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users | flatten(levels=1) }}"
