---
- name: "Prepare tmp folder"
  ansible.builtin.file:
    state: directory
    mode: '0755'
    path: "{{ tmp_dir }}"

- name: "Prepare user-data"
  ansible.builtin.template:
    src: user-data.{{ autoinstall_target | mandatory }}.yml.j2
    mode: '0644'
    dest: "{{ tmp_dir }}/user-data-{{ autoinstall_target }}"
