---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: ce
docker_package:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "containerd.io"
  - "docker-compose-plugin"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: "stable edge"
docker_apt_arch: amd64
docker_apt_ignore_key_error: true
docker_key_source: https://download.docker.com/linux/ubuntu/gpg
docker_key_dest: /etc/apt/trusted.gpg.d/docker.asc

# A list of users who will be added to the docker group.
docker_users:
  - "{{ ansible_user }}"
