---
- name: "Ensure packages are installed" # noqa: package-latest
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.package:
    name:
      - tree
      - httpie
      - smartmontools
      - git
      - net-tools
      - bash-completion
      - exa
      - apt-utils
      - lm-sensors
    state: latest
    update_cache: true
