---
- name: "Configure GRUB"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT.*$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_line }}"'
