---
- name: Update packages
  ansible.builtin.shell: |
    opkg update
  when:
    - skip_install | default(false) == false

# - name: Remove packages
#   community.general.opkg:
#     name: "{{ item }}"
#     state: absent
#   retries: 5
#   delay: 1
#   register: result
#   until: result is succeeded
#   loop:
#     - luci-ssl
#     - libustream-wolfssl20201210
#   when:
#     - skip_install | default(false) == false

- name: Install packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
  loop:
    # - luci-ssl-openssl
    - acme
    - luci-app-acme
    - acme-dnsapi
  when:
    - skip_install | default(false) == false
