---
- name: "Install Docker requirements"
  ansible.builtin.include_tasks: requirements.yml

- name: "Install Docker"
  ansible.builtin.include_tasks: install.yml

- name: "Configure Docker"
  ansible.builtin.include_tasks: users.yml
  when:
    - docker_users is defined
    - docker_users | length > 0
