---
- name: Install packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
    update_cache: yes
  retries: 5
  delay: 1
  register: result
  until: result is succeeded
  loop:
    - luci-app-uhttpd
  when:
    - skip_install | default(false) == false
