---
- name: "Create 90-rs-proxmox.conf"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/90-rs-proxmox.conf
    block: |
      # Default: 1048576
      fs.nr_open = 2097152
      # Default: 8388608
      fs.inotify.max_queued_events = 8388608
      # Default: 65536
      fs.inotify.max_user_instances = 1048576
      # Default: 4194304
      fs.inotify.max_user_watches = 4194304
      # Default: 262144
      vm.max_map_count = 262144
    state: present
    create: true
    mode: "0644"

- name: "Create 90-rs-proxmox.conf"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.blockinfile:
    path: /etc/security/limits.d/90-rs-proxmox.conf
    block: |
      *       soft    nofile  1048576
      *       hard    nofile  2097152
      root    soft    nofile  1048576
      root    hard    nofile  2097152
      *       soft    memlock 1048576
      *       hard    memlock 2097152
    state: present
    create: true
    mode: "0644"

- name: "Create /etc/systemd/system/pvedaemon.service.d"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.file:
    path: /etc/systemd/system/pvedaemon.service.d
    state: directory
    mode: "0755"

- name: "Create /etc/systemd/system/pvedaemon.service.d/limits.conf"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/pvedaemon.service.d/limits.conf
    block: |
      [Service]
      LimitNOFILE=infinity
      LimitMEMLOCK=infinity
      LimitNPROC=infinity
      TasksMax=infinity
    state: present
    create: true
    mode: "0644"

- name: "Create /etc/systemd/system/pve-guests.service.d"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.file:
    path: /etc/systemd/system/pve-guests.service.d
    state: directory
    mode: "0755"

- name: "Create /etc/systemd/system/pve-guests.service.d/limits.conf"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/pve-guests.service.d/limits.conf
    block: |
      [Service]
      LimitNOFILE=infinity
      LimitMEMLOCK=infinity
      LimitNPROC=infinity
      TasksMax=infinity
    state: present
    create: true
    mode: "0644"

- name: "Create /etc/systemd/system/pve-ha-lrm.service.d"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.file:
    path: /etc/systemd/system/pve-ha-lrm.service.d
    state: directory
    mode: "0755"

- name: "Create /etc/systemd/system/pve-ha-lrm.service.d/limits.conf"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/pve-ha-lrm.service.d/limits.conf
    block: |
      [Service]
      LimitNOFILE=infinity
      LimitMEMLOCK=infinity
      LimitNPROC=infinity
      TasksMax=infinity
    state: present
    create: true
    mode: "0644"

- name: "Reload systemd"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart pvedaemon"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - pvedaemon.service
    - pve-ha-lrm.service
