---
- name: "Ensure packages are installed # noqa: package-latest"
  become: "{{ __become | default(true) | bool }}"
  ansible.builtin.package:
    name:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
      - git
    state: latest
    update_cache: true
